### ISSUE TITLE
Add character parser for myth-weavers.com

### ISSUE THREAD

**Issue by chielk** [chielk/dndmake#8]
Change character_from_url so that it can download from different sites. Add a parser for myth-weavers.com

For reference: http://www.myth-weavers.com/sheet.html#id=62391

**Comment by pkok** [comment]
Okay, maybe I shouldn't be assigned to this.

The difficulty with the Myth Weavers sheets is that it is dynamically loaded with some JavaScript magic. I have no idea how to simulate a JavaScript engine through Python.

**Comment by chielk** [comment]
I've looked through the resources and found that all the data can just be loaded without HTML stuff. E.g.
http://www.myth-weavers.com/sheets/62391 returns a json object that can be parsed in Python.

**Comment by chielk** [comment]
Probably fixed with ddb17f2. Testing will be part of #10.
